theme = "blowfish"
baseURL = "https://ishiharatma.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[minify]
  minifyOutput = true
