baseURL = "https://ishiharatma.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "issy's Portfolio"
theme = "jekyll-theme-chirpy"
#theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "issy"
  description = "Cloud Engineer and others"
  avatarURL = "/images/top.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  accentColor = "#38b48b"
  togglePreviousAndNextButtons = "true"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/tomoaki-ishihara-a48232203/"},
    {name = "x", url = "https://twitter.com/issy55829654"},
    {name = "github", url = "https://github.com/ishiharatma"},
    {name = "devdotto", url = "https://dev.to/issy929"},
    {name = "zenn", url = "https://zenn.dev/issy"},
  ]
  metaKeywords = ["ishiharatma", "issy", "portfolio"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Card"
    pre = "<span data-feather='user'></span>"
    url = "/card/"
    weight = 3

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight =2

  [[menu.main]]
    name = "Activity"
    pre = "<span data-feather='activity'></span>"
    url = "/activities/"
    weight = 4

  [[menu.main]]
    name = "Post"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    # Unique identifiers are required for menu entries without a name property,
    # or for menu entries which re-use a name
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    # Absolute URL to external resource
    url = "https://github.com/ishiharatma"
    weight = 6

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "https://zenn.dev/issy/feed"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[minify]
    minifyOutput = true
